INSERT INTO PARTICIPANTE_TB(NOME,EMAIL)VALUES('José Silva','jose@gmail.com');
INSERT INTO PARTICIPANTE_TB(NOME,EMAIL)VALUES('Tiago faria','tiagofaria@gmail.com');
INSERT INTO PARTICIPANTE_TB(NOME,EMAIL)VALUES('Maria do Rosario','maria@gmail.com');
INSERT INTO PARTICIPANTE_TB(NOME,EMAIL)VALUES('Teresa Silva','teresa@gmail.com');

INSERT INTO CATEGORIA_TB(descricao)VALUES('Curso');
INSERT INTO CATEGORIA_TB(descricao)VALUES('Oficina');

INSERT INTO ATIVIDADE_TB(NOME,DESCRICAO,PRECO,CATEGORIA_ID)VALUES('Curso de HTML','Aprenda HTML na pratica','80.00','1');
INSERT INTO TB_ATIVIDADE_PARTICIPANTE (ATIVIDADE_ID,PARTICIPANTE_ID )VALUES('1','1');
INSERT INTO TB_ATIVIDADE_PARTICIPANTE (ATIVIDADE_ID,PARTICIPANTE_ID )VALUES('1','2');
INSERT INTO TB_ATIVIDADE_PARTICIPANTE (ATIVIDADE_ID,PARTICIPANTE_ID )VALUES('1','3');
INSERT INTO BLOCO_TB(INICIO,FIM,ATIVIDADE_ID)VALUES(TIMESTAMP WITH TIME ZONE '2017-09-25T08:00:00Z',TIMESTAMP WITH TIME ZONE '2017-09-25T11:00:00Z','1');



INSERT INTO ATIVIDADE_TB(NOME,DESCRICAO,PRECO,CATEGORIA_ID)VALUES('Oficina de Github','Controle versões de seus projetos','80.00','2');

INSERT INTO TB_ATIVIDADE_PARTICIPANTE (ATIVIDADE_ID,PARTICIPANTE_ID )VALUES('2','3');
INSERT INTO TB_ATIVIDADE_PARTICIPANTE (ATIVIDADE_ID,PARTICIPANTE_ID )VALUES('2','4');

INSERT INTO BLOCO_TB(INICIO,FIM,ATIVIDADE_ID)VALUES(TIMESTAMP WITH TIME ZONE '2017-09-25T14:00:00Z',TIMESTAMP WITH TIME ZONE '2017-09-25T18:00:00Z','2');
INSERT INTO BLOCO_TB(INICIO,FIM,ATIVIDADE_ID)VALUES(TIMESTAMP WITH TIME ZONE '2017-09-26T11:00:00Z',TIMESTAMP WITH TIME ZONE '2017-09-26T11:00:00Z','2');
